Repository KenanKonjic/space-shuffle-fe, pull requests merged in 2023-06, with the labels that each got.

#23 Frontend design update
  src/app/choose-role/choose-role.component.css
  src/app/choose-role/choose-role.component.html
  src/app/home/home.component.css
  src/app/home/home.component.html
  src/assets/Shuffle.png
  src/assets/driver.png
  src/assets/drrrri.png
  src/assets/formbcg.jpg
  src/assets/passeen.png
  src/assets/passenger.png
  src/assets/rocket-png-40811.png
  src/assets/rockkkkkkk.png
Labels: update

#24 Fixed: Routing on login and signup
  src/app/login/login-response.interface.ts
  src/app/login/login.component.html
  src/app/login/login.component.ts
  src/app/signup/signup.component.html
  src/app/signup/signup.component.ts
Labels: bug, enhancement

#33 Responsiveness update + Added pickup page
  src/app/admin-panel/admin-panel.component.css
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/choose-ride/choose-ride.component.css
  src/app/choose-ride/choose-ride.component.html
  src/app/choose-ride/choose-ride.component.ts
  src/app/choose-role/choose-role.component.css
  src/app/header/header.component.css
  src/app/header/header.component.html
  src/app/header/header.component.ts
  src/app/home/home.component.css
  src/app/home/home.component.html
  src/app/login/login.component.css
  src/app/login/login.component.html
  src/app/login/login.component.ts
  src/app/models/pickup.model.ts
  src/app/poppup/poppup.component.css
  src/app/poppup/poppup.component.html
  src/app/poppup/poppup.component.ts
  src/app/services/ride.service.ts
  src/app/signup/signup.component.css
  src/app/signup/signup.component.html
  src/app/signup/signup.component.ts
Labels: update

#35 UserProfile logic on FE
  src/app/models/user.model.ts
  src/app/resolvers/user.resolver.ts
  src/app/services/user.service.ts
  src/app/user-profile/user-profile.component.html
  src/app/user-profile/user-profile.component.ts
Labels: enhancement
